spring:
  datasource:
    #url: jdbc:mariadb://host.docker.internal:3306/demo_board?characterEncoding=UTF-8
    url: jdbc:mariadb://127.0.0.1:3306/demo_board?characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: osckorea!

server:
  port: 7077