version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - board-mysql-data:/var/lib/mysql
      - ../src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      LANG: C.UTF-8
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: osckorea!
      MYSQL_DATABASE: demo_board
      MYSQL_USER: board
      MYSQL_PASSWORD: osckorea!
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
volumes:
  board-mysql-data: