apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-deploy.yaml
  - my-tcp-services.yaml
  - mysql-ingress.yaml
  - demo-api.yaml
  - demo-api-cm.yaml

images:
  - name: jei0486/demo-api
    newTag: v4